site_name: 3DS Hacks Guide
theme: 
    name: material
copyright: Copyright &copy; 2021 <a href="https://discord.gg/C29hYvh" target="_blank">Nintendo Homebrew</a>, Maintained by the <a href="/Guide-3DS_mkdocs/credits">NH Discord Server</a>.
site_description: 3DS Hacks Guide.
site_author: NH Discord Server.
site_url: https://githubpages.hansol.ca/

nav:
    - Home                  : index.md
    - User Guide:
        - 'Get Started'     : 'user-guide/get-started.md'
        - Methods: 
            - 'Soundhax'    : 'user-guide/installing-boot9strap-(soundhax).md'  
            - 'Seedminer'   : 'user-guide/seedminer.md'
        - 'Finalizing Setup': finalizing-setup.md
    - Extras:
        - 'A9LH to B9S'              : 'extras/a9lh-to-b9s.md'
        - 'Checking for CFW'         : 'extras/checking-for-cfw.md'
        - 'CTRtransfer'              : 'extras/ctrtransfer.md'
        - 'GodMode9 Usage'           : 'extras/godmode9-usage.md'
        - 'Move EmuNAND'             : 'extras/move-emunand.md'
        - 'NSUI'                     : 'extras/nsui.md'
        - 'Region Changing'          : 'extras/region-changing.md'
        - 'Restoring / Updating CFW' : 'extras/restoring-updating-cfw.md'
        - 'Updating B9S'             : 'extras/updating-b9s.md'
        - 'Uninstall CFW'            : 'extras/uninstall-cfw.md'
    - FAQ                   : faq.md
    - Troubleshooting       : troubleshooting.md
    - Credits               : credits.md
    - Privacy Policy        : privacy-policy.md
    
markdown_extensions:
    - admonition
    - fontawesome_markdown

